use datathon;

CREATE TABLE USER(
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  PASS VARCHAR(255),
  ROLE ENUM('CUSTOMER','ADMIN')
);

CREATE TABLE PLACE(
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  LATITUDE FLOAT NOT NULL,
  LONGITUDE FLOAT NOT NULL
);

CREATE TABLE USER_PLACE (
  USER_ID INT(11) NOT NULL,
  PLACE_ID INT(11) NOT NULL,
  CONSTRAINT UNIQUE KEY(USER_ID, PLACE_ID),
  CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID)
);

CREATE TABLE CONTAINER (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PLACE_ID INT(11) NOT NULL,
  CONSTRAINT FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID)
);

CREATE TABLE NOTIFICATION_FROM_USER (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT(11) NOT NULL,
  CONTAINER_ID INT(11) NOT NULL,
  TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ACTIVITY ENUM('IS_FULL', 'EMPTIED'),
  CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FOREIGN KEY (CONTAINER_ID) REFERENCES CONTAINER(ID)
);
